export const WEBHOOK_EVENTS = [
  "client_created",
  "client_updated",
  "client_deleted",
  "organization_created",
  "organization_updated",
  "template_created",
  "template_updated",
  "template_set_as_default",
  "campaign_created",
  "campaign_submitted_for_approval",
  "campaign_approved",
  "campaign_rejected",
  "campaign_released",
  "campaign_sending_started",
  "campaign_completed",
  "campaign_failed",
  "campaign_report_added",
  "contact_list_uploaded",
  "contact_list_validated",
] as const;

export type WebhookEvent = (typeof WEBHOOK_EVENTS)[number];

export const WEBHOOK_EVENT_LABELS: Record<WebhookEvent, string> = {
  client_created: "Cliente criado",
  client_updated: "Cliente atualizado",
  client_deleted: "Cliente excluído",
  organization_created: "Organização criada",
  organization_updated: "Organização atualizada",
  template_created: "Template criado",
  template_updated: "Template atualizado",
  template_set_as_default: "Template marcado como padrão",
  campaign_created: "Campanha criada (rascunho)",
  campaign_submitted_for_approval: "Campanha enviada para aprovação",
  campaign_approved: "Campanha aprovada",
  campaign_rejected: "Campanha rejeitada",
  campaign_released: "Campanha liberada",
  campaign_sending_started: "Disparo iniciado (callback n8n)",
  campaign_completed: "Disparo concluído (callback n8n)",
  campaign_failed: "Disparo com falha (callback n8n)",
  campaign_report_added: "Relatório de disparo adicionado",
  contact_list_uploaded: "Lista de contatos enviada",
  contact_list_validated: "Lista de contatos validada",
};
